[TOS-4919] Allow agent checkout git repository with branch in format abc/def
katalon-studio/katalon-agent pull request #78
Opened 2022-06-09 07:30 UTC by thanhnle

![image](https://user-images.githubusercontent.com/93516707/172790268-cb30966d-3e66-44b0-89b3-552386c916d8.png)

2022-06-09 07:35 UTC, TuanNguyen-Dev14 approved these changes

2022-06-09 07:48 UTC, lequangtrai approved these changes

2022-06-09 09:29 UTC, huynguyen2908 approved these changes

2022-06-13 03:24 UTC, quidl approved these changes

2022-06-13 03:24 UTC, merged

2022-06-13 03:26 UTC, anhqle1996 requested changes

2022-06-13 03:26 UTC, anhqle1996 commented on src/core/file.js
> +    if (branch.includes(refsHeads)) {
should use startWith

2022-06-13 03:28 UTC, thanhnle commented on src/core/file.js
> +    if (branch.includes(refsHeads)) {
thanks chị, startsWith is better